apiVersion: apps/v1
kind: Deployment
metadata:
  name: monapp-deployment
  labels:
    app: monapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monapp
  template:
    metadata:
      labels:
        app: monapp
    spec:
      containers:
      - name: monapp
        image: phenixdotnet.azurecr.io/monapp:config
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: monapp-config-env-file
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 128Mi
      imagePullSecrets:
        - name: phenixdotnetregistry
