apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-deployment
  labels:
    app: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: consul
        ports:
        - containerPort: 8500
        - containerPort: 8200

---
kind: Service
apiVersion: v1
metadata:
  name: consul
spec:
  selector:
    app: consul
  ports:
  - protocol: TCP
    name: ui
    port: 8500
    targetPort: 8500
  - protocol: TCP
    name: app
    port: 8200
    targetPort: 8200